// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/actions": {
            "get": {
                "responses": {}
            },
            "post": {
                "responses": {}
            }
        },
        "/api/actions/:id": {
            "get": {
                "responses": {}
            },
            "delete": {
                "responses": {}
            }
        },
        "/api/auth/register": {
            "post": {
                "responses": {}
            }
        },
        "/api/close-reasons": {
            "get": {
                "responses": {}
            },
            "post": {
                "responses": {}
            }
        },
        "/api/close-reasons/:id": {
            "get": {
                "responses": {}
            },
            "put": {
                "responses": {}
            },
            "delete": {
                "responses": {}
            }
        },
        "/api/permission": {
            "post": {
                "responses": {}
            }
        },
        "/api/permission/:id": {
            "get": {
                "responses": {}
            },
            "delete": {
                "responses": {}
            }
        },
        "/api/permissions": {
            "get": {
                "responses": {}
            }
        },
        "/api/resources": {
            "get": {
                "responses": {}
            },
            "post": {
                "responses": {}
            }
        },
        "/api/resources/:id": {
            "get": {
                "responses": {}
            },
            "delete": {
                "responses": {}
            }
        },
        "/api/roles": {
            "get": {
                "responses": {}
            },
            "post": {
                "responses": {}
            }
        },
        "/api/roles-permissions": {
            "get": {
                "responses": {}
            },
            "put": {
                "responses": {}
            }
        },
        "/api/roles/:id": {
            "get": {
                "responses": {}
            },
            "put": {
                "responses": {}
            },
            "delete": {
                "responses": {}
            }
        },
        "/api/users": {
            "post": {
                "responses": {}
            }
        },
        "/api/users/:id": {
            "put": {
                "responses": {}
            },
            "delete": {
                "responses": {}
            }
        },
        "/api/v1/auth/login": {
            "post": {
                "responses": {}
            }
        },
        "/api/v1/auth/logout": {
            "post": {
                "responses": {}
            }
        },
        "/api/v1/auth/me": {
            "get": {
                "responses": {}
            }
        },
        "/api/v1/auth/refresh-token": {
            "post": {
                "responses": {}
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
