info:
  contact: {}
paths:
  /api/actions:
    get:
      responses: {}
    post:
      responses: {}
  /api/actions/:id:
    delete:
      responses: {}
    get:
      responses: {}
  /api/auth/register:
    post:
      responses: {}
  /api/close-reasons:
    get:
      responses: {}
    post:
      responses: {}
  /api/close-reasons/:id:
    delete:
      responses: {}
    get:
      responses: {}
    put:
      responses: {}
  /api/permission:
    post:
      responses: {}
  /api/permission/:id:
    delete:
      responses: {}
    get:
      responses: {}
  /api/permissions:
    get:
      responses: {}
  /api/resources:
    get:
      responses: {}
    post:
      responses: {}
  /api/resources/:id:
    delete:
      responses: {}
    get:
      responses: {}
  /api/roles:
    get:
      responses: {}
    post:
      responses: {}
  /api/roles-permissions:
    get:
      responses: {}
    put:
      responses: {}
  /api/roles/:id:
    delete:
      responses: {}
    get:
      responses: {}
    put:
      responses: {}
  /api/users:
    post:
      responses: {}
  /api/users/:id:
    delete:
      responses: {}
    put:
      responses: {}
  /api/v1/auth/login:
    post:
      responses: {}
  /api/v1/auth/logout:
    post:
      responses: {}
  /api/v1/auth/me:
    get:
      responses: {}
  /api/v1/auth/refresh-token:
    post:
      responses: {}
swagger: "2.0"
