const { VITE_API_URL, VITE_DEV, VITE_DOMAIN } = import.meta.env

export const CONFIG = {
  isProduction: VITE_DEV === 'false',
  isDevelopment: VITE_DEV === 'true',
  title: 'Mazic',
  apiURL: VITE_API_URL || 'http://localhost:3000',
  domain: VITE_DOMAIN || 'http://localhost:4200',
  TIME: {
    DD_MM_YYYY: 'DD/MM/YYYY',
  },
  pageSizeList: [5, 10, 20, 30, 40, 50],
  pagination: {
    pageIndex: 0,
    page: 1,
    pageSize: 10,
  },
  sortSeparator: ':',
  stringItemsSeparator: ',',
  appStorage: {
    key: 'app_storage',
  },
}

export const PATH_ROUTE = {
  dashboard: '/',
  home: '/',
  widget: '/widget/:api_key',
} as const

export const PATH_API = {
  logout: '/auth/logout',
  login: '/auth/login',
  register: '/auth/register',
  refreshToken: '/auth/refresh-token',
} as const

export enum HTTP_CODE {
  Continue = 100,
  SwitchingProtocols = 101,
  Processing = 102,
  EarlyHints = 103,
  Ok = 200,
  Created = 201,
  Accepted = 202,
  NonAuthoritativeInformation = 203,
  NoContent = 204,
  ResetContent = 205,
  PartialContent = 206,
  MultiStatus = 207,
  AlreadyReported = 208,
  ImUsed = 226,
  MultipleChoices = 300,
  MovedPermanently = 301,
  Found = 302,
  SeeOther = 303,
  NotModified = 304,
  UseProxy = 305,
  Unused = 306,
  TemporaryRedirect = 307,
  PermanentRedirect = 308,
  BadRequest = 400,
  Unauthorized = 401,
  PaymentRequired = 402,
  Forbidden = 403,
  NotFound = 404,
  MethodNotAllowed = 405,
  NotAcceptable = 406,
  ProxyAuthenticationRequired = 407,
  RequestTimeout = 408,
  Conflict = 409,
  Gone = 410,
  LengthRequired = 411,
  PreconditionFailed = 412,
  PayloadTooLarge = 413,
  UriTooLong = 414,
  UnsupportedMediaType = 415,
  RangeNotSatisfiable = 416,
  ExpectationFailed = 417,
  ImATeapot = 418,
  MisdirectedRequest = 421,
  UnprocessableEntity = 422,
  Locked = 423,
  FailedDependency = 424,
  TooEarly = 425,
  UpgradeRequired = 426,
  PreconditionRequired = 428,
  TooManyRequests = 429,
  RequestHeaderFieldsTooLarge = 431,
  UnavailableForLegalReasons = 451,
  InternalServerError = 500,
  NotImplemented = 501,
  BadGateway = 502,
  ServiceUnavailable = 503,
  GatewayTimeout = 504,
  HttpVersionNotSupported = 505,
  VariantAlsoNegotiates = 506,
  InsufficientStorage = 507,
  LoopDetected = 508,
  NotExtended = 510,
  NetworkAuthenticationRequired = 511,
}
