name: mazic-habit

services:
  mazic-server:
    image: phidndev/dev:mazic_server_v0
    volumes:
      - ./mz_data:/app/packages/mazic-server/mz_data
    ports:
      - "8090:8090"
    environment:
      APP_ENV: production
