name: deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ./packages/mazic-docker/Dockerfile
          tags: phidndev/dev:mazic_server_v0
          secrets: |
            "VITE_DEV=false"
            "VITE_DOMAIN=${{ secrets.VITE_DOMAIN }}"
            "VITE_API_URL=${{ secrets.VITE_API_URL }}"

            "APP_ENV=production"
            "APP_DOMAIN=${{ secrets.APP_DOMAIN }}"
            "APP_NAME=${{ secrets.APP_NAME }}"

            "JWT_PRIVATE_KEY=${{ secrets.JWT_PRIVATE_KEY }}"
            "JWT_PUBLIC_KEY=${{ secrets.JWT_PUBLIC_KEY }}"
            "ACCESS_TOKEN_EXPIRED_IN=168h"
            "REFRESH_TOKEN_EXPIRED_IN=720h"
            "BCRYPT_COST=10"

            "SUPABASE_URL=${{ secrets.SUPABASE_URL }}"
            "SUPABASE_BUCKET=${{ secrets.SUPABASE_BUCKET }}"
            "SUPABASE_SERVICE_ROLE=${{ secrets.SUPABASE_SERVICE_ROLE }}"

            "SMTP_HOST=${{ secrets.SMTP_HOST }}"
            "SMTP_PORT=${{ secrets.SMTP_PORT }}"
            "SMTP_USERNAME=${{ secrets.SMTP_USERNAME }}"
            "SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }}"
            "SMTP_TLS=${{ secrets.SMTP_TLS }}"
            "SMTP_SENDER_NAME=${{ secrets.SMTP_SENDER_NAME }}"
            "SMTP_SENDER_ADDR=${{ secrets.SMTP_SENDER_ADDR }}"

            "S3_ACCESS=${{ secrets.S3_ACCESS }}"
            "S3_SECRET=${{ secrets.S3_SECRET }}"
            "S3_BUCKET=${{ secrets.S3_BUCKET }}"
            "S3_REGION=${{ secrets.S3_REGION }}"
            "S3_ENDPOINT=${{ secrets.S3_ENDPOINT }}"

      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/mazic_habit
            docker remove -f mazic-server || true
            docker image rm -f phidndev/dev:mazic_server_v0 || true
            docker run -d --name mazic-server -v ./mz_data:/app/packages/mazic-server/mz_data -p 8090:8090 -e APP_ENV=production phidndev/dev:mazic_server_v0
