name: deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ./packages/mazic-docker/Dockerfile
          tags: phidndev/dev:mazic_server_v0
          secrets: |
            "VITE_DEV=false"
            "VITE_BASE=/web"
            "VITE_DOMAIN=${{ secrets.VITE_DOMAIN }}"
            "VITE_API_URL=${{ secrets.VITE_API_URL }}"

            "APP_ENV=production"
            "APP_DOMAIN=${{ secrets.APP_DOMAIN }}"
            "JWT_PRIVATE_KEY=${{ secrets.JWT_PRIVATE_KEY }}"
            "JWT_PUBLIC_KEY=${{ secrets.JWT_PUBLIC_KEY }}"
            "ACCESS_TOKEN_EXPIRED_IN=168h"
            "REFRESH_TOKEN_EXPIRED_IN=720h"
            "BCRYPT_COST=10"
            "SUPABASE_URL=${{ secrets.SUPABASE_URL }}"
            "SUPABASE_BUCKET=${{ secrets.SUPABASE_BUCKET }}"
            "SUPABASE_SERVICE_ROLE=${{ secrets.SUPABASE_SERVICE_ROLE }}"

      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            whoami
            ls -al
